[COM-51717, PXS-60201] Scala 2.11 -> Scala 2.13
paytronix/utils-open pull request #25
Opened 2021-10-29 21:29 UTC by aldiyen

2021-10-29 21:32 UTC, aldiyen commented
Don't merge this.

2021-11-03 21:42 UTC, sc8ing requested changes

2021-11-03 21:42 UTC, sc8ing commented on interchange/liftjson/src/test/scala/com/paytronix/utils/interchange/format/liftjson/coderSpecs.scala
>      }
What's the reasoning for this?

2021-11-03 21:42 UTC, sc8ing commented on pom.xml
> +        <lift.version>2.6.3-px</lift.version>
Wait what

2021-11-03 21:42 UTC, sc8ing commented on pom.xml
> +                            <artifactId>kind-projector_${scala.version}</artifactId>
Don't we usually use `${scala.compatibility.version}` instead of `${scala.version}`?

2021-11-03 21:42 UTC, sc8ing commented on pom.xml
>                                  <!--<arg>-Ymacro-debug-lite</arg>-->
Can probably remove these now I'm assuming?

2021-11-03 21:42 UTC, sc8ing commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> -import scalaz.{\/, -\/, \/-, Applicative, Foldable, Monad, MonadError, Traverse, Functor, Scalaz}
Are we just getting rid of all scalaz stuff in this upgrade?

2021-11-03 21:42 UTC, sc8ing commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> +        implicit def resultGTraverse[E](implicit app: Applicative[ResultG[E, *]]) = {
Hopefully the kind projector works on jenkins now...

2021-11-03 21:42 UTC, sc8ing commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> +        }
Great!

2021-11-03 21:42 UTC, sc8ing commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> +            }
Or just `...:ResultT[Option, Int] = ResultT[Option, Int](maybeOkInt).map(_ + 1)`? (and similarly for the above example). It seems better to encourage people to not use `for` for everything when it doesn't really make the code more readable.

2021-11-03 21:42 UTC, sc8ing commented on scala/src/test/scala/com/paytronix/utils/scala/ResultSpecs.scala
> +import cats.syntax._
Woah Matt! Welcome to the dark side

2021-11-03 21:42 UTC, sc8ing commented on scala/src/test/scala/com/paytronix/utils/scala/ResultSpecs.scala
> + * trouble finding it.
I would imagine it has to be done explicitly.

2021-11-03 21:42 UTC, sc8ing commented on validation/src/main/scala/com/paytronix/utils/validation/column.scala
> +//    type Columns = List[(String, Int)]
Commented out code here, and below

2021-11-03 21:45 UTC, aldiyen commented on interchange/avro/src/main/scala/com/paytronix/utils/interchange/format/avro/utils.scala
> +        }
I'm with you. If you can find another solution feel free to implement it!

2021-11-03 21:47 UTC, aldiyen commented on interchange/avro/src/main/scala/com/paytronix/utils/interchange/format/avro/package.scala
> +    def mapWithConverter[B](converter: TypeConverter[B, A]): AvroCoder[B] = AvroCoder.make(encode.mapKleisli(converter.to), decode.mapKleisli(converter.from))
Because it's not actually a bijection. Bijections require that there be a 1:1 correspondence between both types, and this does not guarantee that.

2021-11-03 21:47 UTC, aldiyen commented on interchange/base/src/main/scala/com/paytronix/utils/interchange/base/package.scala
> +    class name(val name: String) extends StaticAnnotation
Makes the field public.

2021-11-03 21:47 UTC, aldiyen commented on interchange/json/src/main/scala/com/paytronix/utils/interchange/format/json/container.scala
> +                                            case other@_ =>
It logs a warning if you bind something to a name and don't use it unless you do this.

2021-11-03 21:50 UTC, aldiyen commented on interchange/liftjson/src/test/scala/com/paytronix/utils/interchange/format/liftjson/coderSpecs.scala
>      }
Uhh this is a very old change but I think in some newer version of Lift which I never ended up using, `JField` is not a `JValue` and can only be a member of `JObject`. This makes sense to me, but I suppose maybe I should change it back since I'm still assuming we're using Lift 2.6.3. I dunno... you should never really have a JField in isolation because it doesn't actually represent valid JSON.

2021-11-03 21:50 UTC, aldiyen commented on pom.xml
> +        <lift.version>2.6.3-px</lift.version>
What what?

2021-11-03 21:50 UTC, aldiyen commented on pom.xml
> +                            <artifactId>kind-projector_${scala.version}</artifactId>
Yes but not for this.

2021-11-03 21:51 UTC, aldiyen commented on pom.xml
>                                  <!--<arg>-Ymacro-debug-lite</arg>-->
macro-debug-lite, if it's still supported, is still useful for debugging macros that aren't working so I'd just leave it... unless this compiler flag was removed, in which case I agree with you.

2021-11-03 21:51 UTC, aldiyen commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> -import scalaz.{\/, -\/, \/-, Applicative, Foldable, Monad, MonadError, Traverse, Functor, Scalaz}
Yes

2021-11-03 21:51 UTC, aldiyen commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> +        implicit def resultGTraverse[E](implicit app: Applicative[ResultG[E, *]]) = {
I bet it could've been fixed before. I will fix it if it continues to fail.

2021-11-03 21:52 UTC, aldiyen commented on scala/src/main/scala/com/paytronix/utils/scala/result.scala
> +            }
I don't think I wrote this code. Jack did, maybe?

2021-11-03 21:52 UTC, aldiyen commented on scala/src/test/scala/com/paytronix/utils/scala/ResultSpecs.scala
> +import cats.syntax._
I think I was planning to remove this but I dunno. I think I wrote this a while ago...

2021-11-03 21:53 UTC, aldiyen commented on scala/src/test/scala/com/paytronix/utils/scala/ResultSpecs.scala
> + * trouble finding it.
Yeah probably but I didn't feel like spending more time to fix it. I might go back to it, but I don't think it's important now unless it turns out something somewhere else actually uses this.

2021-11-03 21:54 UTC, aldiyen commented on validation/src/main/scala/com/paytronix/utils/validation/column.scala
> +//    type Columns = List[(String, Int)]
This might also have been Jack.

2021-11-03 21:55 UTC, aldiyen commented on validation/src/main/scala/com/paytronix/utils/validation/column.scala
> +//    type Columns = List[(String, Int)]
Nope it was me.

2021-11-04 15:59 UTC, sc8ing commented on interchange/avro/src/main/scala/com/paytronix/utils/interchange/format/avro/package.scala
> +    def mapWithConverter[B](converter: TypeConverter[B, A]): AvroCoder[B] = AvroCoder.make(encode.mapKleisli(converter.to), decode.mapKleisli(converter.from))
I guess that makes sense, though afaik there's simply no possible way to actually guarantee that statically.

2021-11-04 16:05 UTC, aldiyen commented on interchange/avro/src/main/scala/com/paytronix/utils/interchange/format/avro/package.scala
> +    def mapWithConverter[B](converter: TypeConverter[B, A]): AvroCoder[B] = AvroCoder.make(encode.mapKleisli(converter.to), decode.mapKleisli(converter.from))
Well sure but it's not even trying to be a bijection so it seems wrong to call it that.

2021-11-04 19:06 UTC, sc8ing commented on interchange/liftjson/src/test/scala/com/paytronix/utils/interchange/format/liftjson/coderSpecs.scala
>      }
That makes sense. I vote leave it like this personally

2021-11-04 19:06 UTC, sc8ing commented on pom.xml
> +        <lift.version>2.6.3-px</lift.version>
Paytronix maintains a custom version of Lift?

2021-11-04 19:07 UTC, sc8ing commented on pom.xml
> +                            <artifactId>kind-projector_${scala.version}</artifactId>
Out of curiosity why?

2021-11-04 19:17 UTC, aldiyen commented on pom.xml
> +        <lift.version>2.6.3-px</lift.version>
Well it does now because there is no Scala 2.13 build of Lift 2.6.3 and migrating to Lift 3.x would require rewriting almost all of our Lift code, which is not really feasible.

2021-11-04 19:18 UTC, aldiyen commented on pom.xml
> +                            <artifactId>kind-projector_${scala.version}</artifactId>
I don't know. I think it must do something with the generated code that is highly dependent on the specific Scala version. This is how the kind-projector plugin's artifact ID is published. If you look at Maven Central there are separate artifacts for like 10 different Scala 2.13.x versions.

2021-11-04 19:20 UTC, aldiyen commented on interchange/json/src/main/scala/com/paytronix/utils/interchange/format/json/container.scala
> +                                            case other@_ =>
Oh I dunno, I kind of like giving the catch-all a name even if it's not used but the Scala team apparently doesn't agree with me. I don't think I've landed on a consistent answer to this warning though.

2021-11-04 20:27 UTC, sc8ing approved these changes

2021-11-17 19:52 UTC, closed without merging