[PXS-68931] day of week phase 1
paytronix/utils-open pull request #27
Opened 2022-01-05 15:11 UTC by sc8ing

2022-01-10 14:52 UTC, aldiyen requested changes
Looks alright overall, except the version. Also a question.

2022-01-10 14:52 UTC, aldiyen commented on pom.xml
> +        <revision>21.3.20211115-day-of-week</revision>
Version should really be a SNAPSHOT, otherwise Maven and the changeversion script will do the wrong thing.

2022-01-10 14:52 UTC, aldiyen commented on scala/src/main/scala/com/paytronix/utils/scala/zioResultInterop.scala
> +        def apply[R0, E, A](
Why is `R0` a type parameter here if it's never used?

2022-01-10 15:03 UTC, nicholaschaput-marche commented
Looks good to me. Ready to approve once Matt's changes are addressed

2022-01-10 15:50 UTC, sc8ing commented on scala/src/main/scala/com/paytronix/utils/scala/zioResultInterop.scala
> +        def apply[R0, E, A](
No clue – I stole this from zio's source. Seems to work fine without it 🤷 removed.

2022-01-28 18:12 UTC, aldiyen approved these changes

2022-01-28 18:12 UTC, aldiyen commented on pom.xml
> +        <revision>21.3.20211115-day-of-week-SNAPSHOT</revision>
shouldn't really have the `20211115` here but ehhh whatever

2022-01-28 22:06 UTC, aldiyen requested changes

2022-01-28 22:06 UTC, aldiyen commented on scala/src/main/scala/com/paytronix/utils/scala/zioResultInterop.scala
> +    }
Ok I tested this and it's not lazy:
```
scala> import com.paytronix.utils.scala.zioResultInterop.resultToZioTask
import com.paytronix.utils.scala.zioResultInterop.resultToZioTask

scala> import com.paytronix.utils.scala.result._
import com.paytronix.utils.scala.result._

scala> resultToZioTask(Okay {println("test"); ()})
test
res0: zio.Task[Unit] = zio.ZIO$Succeed@579ee82
```

2022-02-09 21:48 UTC, aldiyen approved these changes

2022-03-02 20:09 UTC, bebingando approved these changes

2022-03-02 20:10 UTC, merged