[PXS-66810] Put the ResultGMatchers code in its own module which refe…
paytronix/utils-open pull request #28
Opened 2022-02-25 19:07 UTC by acloudmovingby

…rences the parent pom as its parent, but the directory is located inside of scala because Matt E said to do that.

2022-03-03 04:03 UTC, bebingando commented on scala/scalatest/pom.xml
> +    Copyright 2012-2020 Paytronix Systems, Inc.
new source file from scratch, should probably just use the current year in this copyright

2022-03-03 05:08 UTC, bebingando reviewed
you need to add a `<module>scala/scalatest</module>` to the modules list in the parent pom.xml or else your new code won't get built and packaged with the project

2022-03-03 05:12 UTC, bebingando requested changes
see my prior comment

2022-03-22 18:14 UTC, bebingando commented on scala/scalatest/src/main/scala/com/paytronix/utils/scalatest/ResultGMatchers.scala
> +        s"$left did not fail with message \' $msg \'",
why do you need to escape the single quotes?

2022-03-23 14:24 UTC, acloudmovingby commented on scala/scalatest/src/main/scala/com/paytronix/utils/scalatest/ResultGMatchers.scala
> +        s"$left did not fail with message \' $msg \'",
No idea, I just copied and pasted what was there previously. I can change it if you'd like.

2022-03-24 15:09 UTC, acloudmovingby commented on scala/scalatest/src/main/scala/com/paytronix/utils/scalatest/ResultGMatchers.scala
> +        s"$left did not fail with message \' $msg \'",
Sorry, that's a lame response and obviously anything I put in a PR is my responsibility. I tried it out on the REPL and you're right, they don't need to be escaped. I just removed the '\' characters and pushed the change.

2022-03-31 17:22 UTC, bebingando approved these changes

2022-04-01 20:20 UTC, jthorntonpx approved these changes

2022-04-12 15:50 UTC, merged