[PXS-69768] - supporting PR for zip upgrade in server
paytronix/utils-open pull request #30
Opened 2022-04-28 18:01 UTC by conlonc2

Merge of `qa/PXS-69108_day_of_week_phase_2 `-> `pxs/2022/bespin` for zip upgrade in server

2022-04-28 20:26 UTC, sc8ing approved these changes

2022-04-29 16:58 UTC, sc8ing requested changes

2022-04-29 16:58 UTC, sc8ing commented on pom.xml
> +        <revision>22.1-bespin-day-of-week-phase-2-SNAPSHOT</revision>
Should change this to be dagobah if since the PR's targeting `pxs/2022/dagobah` now.

2022-04-29 17:05 UTC, acloudmovingby approved these changes

2022-04-29 17:11 UTC, sc8ing approved these changes

2022-04-29 17:11 UTC, merged